pool:
  name: Hosted VS2017
steps:
- task: pwsh
  displayName: Prerequisites
  inputs:
    targetType: filePath
    filePath: './build/vsts-prerequisites.ps1'

- task: pwsh
  displayName: Validate
  inputs:
    targetType: filePath
    filePath: './build/vsts-validate.ps1'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit
  condition: always()
